# Generated by Django 4.1.4 on 2022-12-24 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app30", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reg_teach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone_number", models.IntegerField()),
                ("gender", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=100)),
                ("date_joining", models.DateField(max_length=100, unique=True)),
                ("status", models.CharField(max_length=10)),
                ("role", models.CharField(max_length=30)),
                (
                    "login_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app30.login"
                    ),
                ),
            ],
        ),
    ]
