# Generated by Django 4.1.4 on 2022-12-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app30", "0002_reg_teach"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apply_leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(max_length=100, unique=True)),
                ("end_date", models.DateField(max_length=100, unique=True)),
                ("reason", models.CharField(max_length=100)),
            ],
        ),
    ]
