# Generated by Django 4.1.4 on 2023-01-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app30", "0004_teach_leave"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("subject1", models.IntegerField()),
                ("subject2", models.IntegerField()),
                ("subject3", models.IntegerField()),
                ("subject4", models.IntegerField()),
            ],
        ),
    ]
